### ISSUE TITLE
How to return all results or certain number of results?

### ISSUE THREAD

**Issue by UrsaEli** [frrmack/googlesearch#5]
Hi

Is there to control the number of results and list them?

**Comment by MohamedYousof** [comment]
I have the same question

**Comment by MohamedYousof** [comment]
it can be done using the parameter "&start=4 " it will give you results from 4 to 7 and use " &start=8" to get results from 8 to 11 and so on
I made some simple code to automate such process 

```
import requests
import json


class GoogleSearch:
    def __init__(self, query, pages=1):
        self.query = query
        self.pages = pages
        self.search_link = 'http://ajax.googleapis.com/ajax/services/search/web?v=1.0&q=%s' % self.query
        self.results = []
        self.links = []

    def search(self):
        results = []
        links = []

        for i in range(self.pages):
            search_link = self.search_link + '&start=%i' % (i * 4)
            search_resp = requests.get(search_link)
            response_dict = json.loads(search_resp.text)
            results.append(response_dict['responseData']['results'])

        for r in results:
            for x in r:
                links.append(x['url'])
        self.results = results
        self.links = links
```

**Comment by UrsaEli** [comment]
search_query = GoogleSearch();
search_query.init("test", 2000);
search_query.search();

I got this:
`
Traceback (most recent call last):
  File "observe.py", line 32, in <module>
    search_query.search();
  File "observe.py", line 21, in search
    results.append(response_dict['responseData']['results'])
TypeError: 'NoneType' object has no attribute '__getitem__'
`

Can you show us how to print the links?

**Comment by MohamedYousof** [comment]
the function **init** in any class is preserved function to initialize the class so when you create an object of the class which you named " search_query " you have to pass values for parameters included in " **init** " function 
this is a sample code usage for the class

search_query = GoogleSearch(query="your search query here", pages=2) # add the number that fits
search_query.search()
print(search_query.links)

I highly advice you to read about Object Oriented Programming (OOP)

**Comment by UrsaEli** [comment]
TypeError: this constructor takes no arguments

**Comment by MohamedYousof** [comment]
did you copy my code?
give me your full code here

**Comment by UrsaEli** [comment]
yes, I just used your codes.

import requests
import json

class GoogleSearch:
def init(self, query, pages=1):
self.query = query
self.pages = pages
self.search_link = 'http://ajax.googleapis.com/ajax/services/search/web?v=1.0&q=%s' % self.query
self.results = []
self.links = []

def search(self):
    results = []
    links = []

```
for i in range(self.pages):
    search_link = self.search_link + '&start=%i' % (i * 4)
    search_resp = requests.get(search_link)
    response_dict = json.loads(search_resp.text)
    results.append(response_dict['responseData']['results'])

for r in results:
    for x in r:
        links.append(x['url'])
self.results = results
self.links = links`
```

search_query = GoogleSearch(query="test", pages=2000) # add the number that fits
search_query.search()
print(search_query.links)

**Comment by MohamedYousof** [comment]
you have to copy paste the code to avoid typing mistakes, I can see function " **init** " without the " __ " two underscores before and after which is mandatory

**Comment by UrsaEli** [comment]
File "observe.py", line 32, in <module>
    search_query.search()
  File "observe.py", line 21, in search
    results.append(response_dict['responseData']['results'])
TypeError: 'NoneType' object has no attribute `__getitem__`

**Comment by MohamedYousof** [comment]
Unfortunately Google has stopped this API, I got this response 
This API is no longer available.
alternatively you can use web scrapping tools just like the below example 

```
import requests
from bs4 import BeautifulSoup

resp = requests.get('https://news.google.com/news/section?cf=all&ned=us&q=nfl').text

soup = BeautifulSoup(resp, 'html.parser')
# print(soup.find_all('a'))
links = []
for link in soup.find_all('a'):
    url = str(link.get('href'))
    if url.startswith('http') and ('google.com' not in url) and 'youtube.com' not in url and \
            'googlenewsblog.blogspot.com/' not in url:
        links.append(url)

links = set(links)
print(len(links)) 
```

you can replace "&q=" parameter's value with your search query, in this example I am searching for " nfl " you can change as you need

**Comment by UrsaEli** [comment]
This departs from this `googlesearch` package. Too many fragmented solutions. Can we clean it up?

**Comment by MohamedYousof** [comment]
I didn't understand what you mean

**Comment by frrmack** [comment]
The API this module used is no longer available, googlesearch has been now pulled from PyPI. It would need a complete overhaul and rewrite to use the new google API. The last beautifulsoup entry can be helpful if someone is searching for a loosely related alternative, but I am closing this issue, because it is relevant to a now defunct version (due to the API change).
