### ISSUE TITLE
"The Google Web Search API is no longer available."

### ISSUE THREAD

**Issue by tallforasmurf** [frrmack/googlesearch#6]
That's what comes back in `search_response.text`. In full it says, `The Google Web Search API is no longer available. Please migrate to the Google Custom Search API (https://developers.google.com/custom-search/)`

This module is basically dead until that change is made; you should either pull it from PyPI or at least add a note.

**Comment by frrmack** [comment]
googlesearch was using the old api, and would require a complete overhaul to use the new API. So it's been pulled from PyPI.
